### ISSUE TITLE
Fails to build with FFmpeg 7.0

### ISSUE THREAD

**Issue by jbeich** [russelltg/wl-screenrec#72]
Need https://github.com/zmwangx/rust-ffmpeg/pull/178 but also adapt wl-screenrec:
```rust
error[E0432]: unresolved import `ffmpeg::ffi::av_get_default_channel_layout`
  --> src/audio.rs:16:33
   |
16 |     ffi::{av_find_input_format, av_get_default_channel_layout, AVChannelOrder},
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `av_get_default_channel_layout` in the root

error[E0599]: no method named `set_channels` found for struct `ffmpeg::encoder::audio::Audio` in the current scope
   --> src/audio.rs:223:19
    |
223 |         enc_audio.set_channels(enc_audio_channel_layout.channels());
    |                   ^^^^^^^^^^^^ help: there is a method with a similar name: `channels`
```

https://pkg-status.freebsd.org/beefy22/data/140amd64-default-foo/2024-05-04_07h10m46s/logs/errors/wl-screenrec-0.1.3_2.log

**Comment by jbeich** [comment]
Simply updating the crate doesn't work:
```rust
error[E0432]: unresolved import `ffmpeg::ffi::av_get_default_channel_layout`
  --> src/audio.rs:16:33
   |
16 |     ffi::{av_find_input_format, av_get_default_channel_layout, AVChannelOrder},
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `av_get_default_channel_layout` in the root

error[E0599]: no method named `set_channels` found for struct `ffmpeg::encoder::audio::Audio` in the current scope
   --> src/audio.rs:223:19
    |
223 |         enc_audio.set_channels(enc_audio_channel_layout.channels());
    |                   ^^^^^^^^^^^^ help: there is a method with a similar name: `channels`
```

**Comment by russelltg** [comment]
Fixed in 098b9735fbc1db205707ab804d274a2f34c5ac46
